#!/bin/bash

gosh -Ilib -u'util.match' -u'text.znclog.parser' -E'
match *argv*
[ ( _ logroot nw ch yyyy mm dd )
($ for-each (pa$ format #t "~s~%")
 $ parse-file
   logroot nw
   ch yyyy mm dd
   ) ]
' -Eexit - - "$@"
